function y = lpf(x,Fpass,Fstop)
%LPF Low pass filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 8.1 and the Signal Processing Toolbox 6.19.
% Generated on: 01-Aug-2014 15:22:33

persistent Hd;

if isempty(Hd)

    Apass = 1;         % Passband Ripple (dB)
    Astop = 60;        % Stopband Attenuation (dB)
    Fs    = 44.1;  % Sampling Frequency
    
    h = fdesign.lowpass('fp,fst,ap,ast', Fpass, Fstop, Apass, Astop, Fs);
    
    Hd = design(h, 'kaiserwin');
    
    
    
    set(Hd,'PersistentMemory',true);
    
end

y = filter(Hd,x);


