function y = peakFilter(x)
%PEAKFILTER Peak filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 8.1 and the DSP System Toolbox 8.4.
% Generated on: 01-Aug-2014 20:05:37

persistent Hd;

if isempty(Hd)
    
    N     = 6;      % Order
    F0    = 8000;   % Center frequency
    Q     = 2.5;    % Q-factor
    Astop = 50;     % Stopband Attenuation (dB)
    Fs    = 44100;  % Sampling Frequency
    
    h = fdesign.peak('N,F0,Q,Ast', N, F0, Q, Astop, Fs);
    
    Hd = design(h, 'cheby2', ...
        'SOSScaleNorm', 'Linf');
    
    
    
    set(Hd,'PersistentMemory',true);
    
end

y = filter(Hd,x);


